# Generated by Django 5.1.7 on 2025-03-26 19:33

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(upload_to=movies.models.generate_unique_filename),
        ),
    ]
